### ISSUE TITLE
Outfit Generation and Style Extraction via Bidirectional LSTM and Autoencoder

### ISSUE THREAD

**Issue by zyyang** [xthan/polyvore#13]
Hi Xintong,
Check this out:
https://arxiv.org/pdf/1807.03133.pdf

**Comment by xthan** [comment]
Hi, thanks for the link. The added loss seems really interesting.

**Comment by kargarisaac** [comment]
Hi,
Is the code for "Outfit Generation and Style Extraction via Bidirectional LSTM and Autoencoder" available?
