### ISSUE TITLE
possibly wrong parameter order with tf.split

### ISSUE THREAD

**Issue by zyyang** [xthan/polyvore#3]
https://github.com/xthan/polyvore/blob/dd1e03e27fab12ef0051dd2a8ba7a61caaded499/polyvore/polyvore_model_bi.py#L449
 
https://github.com/xthan/polyvore/blob/dd1e03e27fab12ef0051dd2a8ba7a61caaded499/polyvore/polyvore_model_bi.py#L461

could these be:
`f_state_tuple = tf.split(f_state_feed, 2 1)`
`b_state_tuple = tf.split(b_state_feed, 2, 1)`
?

Actually I myself might be confused....

**Comment by xthan** [comment]
You are right, the order is wrong here because I did not test on TF >= 1.0 thoroughly. Will fix it. Thanks!

**Comment by zyyang** [comment]
I trained a 1.x model successfully, but could not run inference, neither.
Thinking about going with Keras.
Any suggestion?

**Comment by xthan** [comment]
What is wrong with your inference? Maybe I can help.

**Comment by zyyang** [comment]
Thanks, Xin Tong.
I trained the model with commit dd1e03e following your description.

But I failed to restoring parameters from model. (I trained on a TitanX server while using the model locally at my Mac.)
The loading goes like(taken from your latter committed code):

`g = tf.Graph()
with g.as_default():
    model_config = configuration.ModelConfig()
    model_config.rnn_type = 'lstm'
    model = polyvore_model.PolyvoreModel(model_config, mode="inference")
    model.build()
    saver = tf.train.Saver()
g.finalize()
sess = tf.Session(graph=g)
saver.restore(sess, 'model.ckpt-99543') # this is what I got after training.`


The error ( ) was like:

`
DataLossError                             Traceback (most recent call last)
<ipython-input-5-5b6a557fd54a> in <module>()
----> 1 saver.restore(sess, 'model.ckpt-99543')
DataLossError: Unable to open table file ./model.ckpt-99543: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_387 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_387/tensor_names, save/RestoreV2_387/shape_and_slices)]]
....
DataLossError (see above for traceback): Unable to open table file ./model.ckpt-99543: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_387 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_387/tensor_names, save/RestoreV2_387/shape_and_slices)]]`

I have no idea about this error. it is hard to debug, so I am planning to re impl your paper in Keras...
