### ISSUE TITLE
ImportError: No module named inception_v3

### ISSUE THREAD

**Issue by hrsma2i** [xthan/polyvore#6]
```
Traceback (most recent call last):
  File "polyvore/run_inference.py", line 28, in <module>
    import polyvore_model_bi as polyvore_model
  File "/root/workdir/tf0.10.0/polyvore/polyvore_model_bi.py", line 29, in <module>
    from ops import image_embedding
  File "/root/workdir/tf0.10.0/polyvore/ops/image_embedding.py", line 25, in <module>
    from tensorflow.contrib.slim.python.slim.nets.inception_v3 import inception_v3_base
ImportError: No module named inception_v3
```

I suppose that tensorflow 0.10.0 doesn't support inception_v3 module.

https://github.com/tensorflow/tensorflow/tree/r0.10/tensorflow/contrib/slim/python/slim/nets

I used the below settings.

- Ubuntu: 14.04
- GPU: NVIDIA GeForce GTX 1080
- architecture: Pascal
- NVIDIA driver: 367.57
- CUDA: 7.5
- cudnn: 5
- python: 2.7.4
- tensorflow: 0.10.0

**Comment by xthan** [comment]
Try 0.11.0. Tensorflow 0.10.0 doesn't support inception_v3 module as I mentioned in the README:

I actually used some version between r0.10 to r0.11 as the first commit of Tensorflow's im2txt, you might need to install r0.11 and modify some functions to run the code. Newer versions of Tensorflow prevent me from doing inference with my old code and restoring my models trained using this version. However, I have a commit that supports training using TensorFlow 1.0 or greater idd1e03e. I will create a new repo supporting TensorFlow version >= 1.0.
